### ISSUE TITLE
Can't load videos

### ISSUE THREAD

**Issue by weole** [SkyTubeTeam/SkyTube#1109] opened 2022-08-25 17:57 UTC
**Describe the bug**
Whenever I try to load a video, it goes into an infinite loading screen.

**Expected behavior**
To play a video when I select it.

**Setup:**
 - Android version: 11
 - Is Your device rooted? No
 - Do You use Tor or any VPN service with your device? No
 - App source github
 - App Version v.2.982
 - App Flavour Extra

**Additional context**
Seems to be happening with newpipe too, don't know if that's relevant or not.

**Comment by gzsombor** [comment] 2022-08-25 20:32
The new release of v2.983 should have a fix for this problem.

**Closed by gzsombor** 2022-08-25 20:32 UTC
Labels: bug

**Comment by GhostEx667** [comment] 2022-08-26 09:47
@gzsombor

Describe the bug
Whenever I try to load a video, it goes into an infinite loading screen.

Expected behavior
To play a video when I select it.

Setup:

Android version: 4.3
Is Your device rooted? No
Do You use Tor or any VPN service with your device? No
App source github
App Version v.2.983

Still doesn't work, 
I can't check, Version 2.984, because I don't have such a device

Do I need to open a new issue ticket?

**Comment by drogga** [comment] 2022-08-26 13:28
@GhostEx667 You now have to use the "SkyTubeLegacy" repo, this one is now for 4.4+, which I suspect that it will not take much time to become 5.0+ and so on not long after (especially if WebView is being used as suggested by some in order to fix the live streams playback)...

**Comment by GhostEx667** [comment] 2022-08-26 14:54
Thanks, I didn't think to check Legacy,
Question removed

**Comment by drogga** [comment] 2022-08-26 15:07
"Question removed" > From whre ?, the comment is still here...

**Comment by drogga** [comment] 2022-08-26 15:08
@GhostEx667 wrote: "Question removed" > From where ?, the comment is still here...
