### ISSUE TITLE
Show Similar videos

### ISSUE THREAD

**Issue by jerryn70** [SkyTubeTeam/SkyTube#358] opened 2018-09-21 15:31 UTC
Instead of opening the video directly, open a new page with that video and show similar videos below the video like YT app

**Comment by papel** [comment] 2019-02-15 02:09
#235 is a similar request.

I think a video recommendation mechanism requires access to the Youtube account, because youtube knows what the user watches and likes and can recommend according to the behavior.

**Comment by gzsombor** [comment] 2021-05-04 07:32
Duplicate of #648

**Closed by gzsombor** 2021-05-04 07:32 UTC
Labels: enhancement
