### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by Git-Forked** [SkyTubeTeam/SkyTube#931] opened 2021-02-16 20:22 UTC
Skytube played first video with audio, but now all other videos have no audio.  All volumes on phone are 100%, and volume in app is 100%.  Still no audio.  Not sure if there is a secret mute button or something that got pressed, but if so it wasn't obvious enough to find it again.

**Comment by gzsombor** [comment] 2021-02-16 20:59
Unable to reproduce without details.

**Comment by BugReportering** [comment] 2021-02-19 02:04
Let me know which details  you would like me to provide and I will attempt to do so to the best of my ability. 
The device used is my S3 (with Android 4.1.2).

**Comment by BugReportering** [comment] 2021-02-19 03:20
Update: I have discovered that not 'ALL' videos are without audio, just many of them.  I have found some videos that do play with audio, so I am thinking that perhaps this is an audio codec issue with the app failing to decode certain audio encodings.

**Comment by drogga** [comment] 2021-02-19 16:14
@BugReportering if you read my comments here (in both open & closed issues), you will find that I still use v2.975 (Extra) exactly because of this issue, which started when the (3) separate rez. settings were implemented, the app now simply uses for the most part 'Dash' streams (m3u's) with separate audio, instead of MP4's with build-in \ muxed ones, and our bricks can't handle WEBM's, it's simple as that...

**Comment by drogga** [comment] 2021-02-19 16:18
@BugReportering if you read my comments here (in both open & closed issues), you will find that I still use v2.975 (Extra) exactly because of this issue, which started when the (3) separate rez. settings were implemented, the app now simply uses for the most part 'Dash' streams (m3u's) with separate audio, instead of MP4's with build-in \ muxed ones, and our bricks can't handle WEBM's, it's simple as that...

Also keep in mind that older vers., like 2.975 can't play 60 FPS or age restricted videos, so you can just forget about those...

**Comment by gzsombor** [comment] 2021-02-25 22:44
So, there are a couple of things, which is missing for me:
* Do you use the Legacy player or the new Default player? (which is the so-called ExoPlayer)
* Have you downloaded the files, or directly playing from the net?
The current - new - logic, is if you are using the Default player **and** you are directly using the net, SkyTube could pick separate video and audio streams. In any other cases, when you downloads the video or use the legacy player directly, it will use a combined audio-video stream. (In theory, it could download the audio/video streams separately, but it's not yet implemented)
 @drogga : I tried the app in emulator, with Android 4 (API 14), but without much success. I could fix the crash, which came from RxJava, but I can't fix the crash from ExoPlayer (Even the old ExoPlayer seems to have parts, where it needs newer API level - and the legacy player also complained about video errors. Unfortunately, it's not clear, if it's because of emulator issues Somewhere I read, that the media player does not work always in older Android versions inside the emulator, so I don't know, how could I test playback, and what kind of formats would work at that API level.

**Comment by drogga** [comment] 2021-02-26 08:33
So here on API 16 (4.1.2, as I haven't tested the app on older than that, tho I have a device with 4.0.3 {API/SDK 15}) I use the app with the "Default Player" (as the name suggests - it's the one set by default) and I don't use the "Legacy Player (unsupported)" one (which IS the actual ExoPlayer, the other "default" one is a custom "new" one, not a system's native and build-in old "Exo", so don't confuse the two), simply because it doesn't have playback speed control and the "Official YouTube Player" one I can't use because it doesn't launch\open at all here (understandable on why - it relies on the YT's embed player activity). Other than that - I don't seem to have issues with the player itself, the problem is specifically from the streams that the app picks now...

BTW I saw that you bumped the minSDKversion of your fork to 16...

**Comment by gzsombor** [comment] 2021-11-15 07:59
The latest release have a configuration to control if you want to use the separate video and audio streams, or you want to  stick with the older formats, with merged streams. Please try it out.

**Closed by gzsombor** 2021-11-15 07:59 UTC
Labels: bug, incomplete

**Comment by drogga** [comment] 2021-11-15 08:19
@gzsombor This response is targeted to the OP right?, not to me, because I'm already using the latest builds that include that option and my other (recent/latest) feedback is based on that.

**Comment by gzsombor** [comment] 2021-11-15 08:28
Yes, that is about the current issue what OP had.

**Comment by manilenio** [comment] 2022-04-02 16:59
> The latest release have a configuration to control if you want to use the separate video and audio streams, or you want to stick with the older formats, with merged streams. Please try it out.

Where can I find this configuration? I don't believe I ever saw this setting. I'm having this problem where the video plays but there's no audio. When I play the same video in newpipe, there's audio. I hope somebody can help.
