### ISSUE TITLE
Add please autostart next video option

### ISSUE THREAD

**Issue by clevertype** [SkyTubeTeam/SkyTube#952] opened 2021-04-05 10:29 UTC
Add please autostart next video after ending (option in settings enable/disable).

**Comment by gzsombor** [comment] 2021-05-04 07:26
There are a couple of trickier question lies behind:
* how to decide what is the next video? Use Youtube's suggestions - if network is available, etc? Or pick the next downloaded video? Or pick the next unseen video from the same channel? 
* do we want to present a selector of X videos to the user before showing the next? 
* etc

**Comment by gzsombor** [comment] 2021-05-04 07:27
It's the duplicate of : #648

**Closed by gzsombor** 2021-05-04 07:27 UTC
Labels: enhancement, help wanted
