### ISSUE TITLE
Skytube closes when importing .Json

### ISSUE THREAD

**Issue by saebaryo-xyz** [SkyTubeTeam/SkyTube#1020] opened 2022-01-12 19:09 UTC
Hi,

It's been a few months that I have been tryi to import my YouTube subscriptions in Json format but evergy time I try from either the main dashboard or the settings it instantly closes the app and I have to open it again.

For info, I am rooted with Magisk 23, and on a Samsung phone that is running Android 11.

Any help would be appreciated, thanks!

**Comment by TheSkallywag** [comment] 2022-02-01 21:47
This happens to me as well on Android 12 Samsung Galaxy Ultra 5G

**Comment by L31FY** [comment] 2022-03-23 00:20
https://github.com/SkyTubeTeam/SkyTube/issues/1033

**Comment by gzsombor** [comment] 2022-04-16 09:45
Probably duplicate of #1046

**Closed by gzsombor** 2022-04-16 09:45 UTC
Labels: bug, duplicate
