### ISSUE TITLE
[Bug/Crash] [Android] App stops responding when importing CSV YouTube Channels subscription

### ISSUE THREAD

**Issue by RFL0WGitPR** [SkyTubeTeam/SkyTube#1043] opened 2022-03-27 03:21 UTC
SkyTube Extra constantly closes on me when I select to import my YouTube Channels .csv file to add Channels to the app 

1. Go to App Preferences on top right corner with the 3 dots tap that

2. Tap on Import/Export

3. Select  Import Subscriptions from YouTube Browse and locate the file on your device for the .csv subscription file from YouTube you downloaded and extracted

4. Select the Subscription.csv file

App closes and I get prompted App not responding 

I expected to see progress bar activity as my YT channel subscriptions from YT account are added to SkyTube Channels Subs.

 - Device: **Motorola One Ace 5G (T-Mobile)**
 - Android version: **10**
 - Device: **Not Rooted**
 -  **Did not use neither Tor or VPN used Google Chrome to download csv from my YouTube Account extracted .zip with Winrar**
 - App source **GitHub**
 - App Version **v2.980**
 - App Flavour **Extra**

**Comment by gzsombor** [comment] 2022-04-16 09:43
Probably duplicate of #1046

**Closed by gzsombor** 2022-04-16 09:43 UTC
Labels: bug, duplicate
