### ISSUE TITLE
Fastlane changelogs have oversize

### ISSUE THREAD

**Issue by IzzySoft** [SkyTubeTeam/SkyTube#1266] opened 2024-05-17 16:06 UTC
Fastlane changelogs are limited to 500 chars (and are truncated at that point, even if it's mid-word). However, yours are more than twice as large:

```
! metadata/free.rm.skytube.extra/en-US/changelogs/48.txt has 1097 chars
```

![image](https://github.com/SkyTubeTeam/SkyTube/assets/6781438/0435d5a2-f458-4eb3-8aa7-ff7605507445)

Could you please take care they stay within those limits? Thanks in advance!

**Comment by drogga** [comment] 2024-05-18 07:36
Duplicate of #1187

_500 chars is a pointless and unnecessary restriction IMO, but at the same time mentioning every translation contributor for changelogs outside of GH._

**Comment by IzzySoft** [comment] 2024-05-18 11:12
> 500 chars is a pointless and unnecessary restriction IMO

Depends whom you ask. I didn't set up that limitation, and there's not much I can do to keep the corresponding tools (which adhere to the definition) from truncating. But to give you an idea why I think it indeed is useful:

![image](https://github.com/SkyTubeTeam/SkyTube/assets/6781438/56af7a9a-4145-4a6c-8275-d8dd94ae6037)

Important details for the latest release are displayed right with the app's description (not only with the IzzyOnDroid repo browser, but also with e.g. the official F-Droid client). One reason for that is to point out e.g. "breaking changes" for updates, so those taking care to look know what to pay attention to. Only the most important things should go into those; so e.g. the translation list could be shortened to "updated translations" – and the entire list then end with "find the full changelog {here}" – with "{here}" being a link to where the full changelog can be found.

IMHO, the per-release changelogs in Fastlane were never intended as "full changelogs" but rather meant for "most important notes on this release".

> Duplicate of

Oops – apologies! Seems like I was distracted (working on the results of the monthly quality check run, there were many projects to report to). I usually perform a search first… But seeing the other issue was opened a year ago, maybe this could be taken care for at least with new releases? :wink:

**Comment by gzsombor** [comment] 2024-07-25 07:16
I'm trying to keep in mind to look for this limitation (of course, the best would be to do automatic validation during the release build, because for 2.990 I forgot to add that file)

**Comment by gzsombor** [comment] 2024-08-27 19:11
A build time check was added, which verifies that there is a fastlane log, and that log is not too long.

**Closed by gzsombor** 2024-08-27 19:11 UTC

**Comment by IzzySoft** [comment] 2024-08-27 21:31
Cool, thanks!
