### ISSUE TITLE
Can't view comments on any video

### ISSUE THREAD

**Issue by arkdae** [SkyTubeTeam/SkyTube#911] opened 2021-02-04 18:09 UTC
For some time I have not been able to view a video's comments. For most of that time, a message popped up, if I remember correctly said, "Error 413: request entity too large." Now it says "Error:reCaptcha Challenge requested."

**Comment by gzsombor** [comment] 2021-02-04 20:08
Could you please include:
* A video URL where it can be reproduced?
* the version of the app? Is it the latest?
* do you get from F-Droid or from Github?
* Is it the OSS or the Extra version?
* Is your phone rooted?
* Do you use Tor or any VPN service with your phone?

**Comment by arkdae** [comment] 2021-02-04 22:18
https://youtu.be/qeBYzTr8_Ls

just a random video from featured.

**Comment by arkdae** [comment] 2021-02-04 22:18
I'm running 2.975, from F-Droid, which shows as the latest. My Lenovo Yogabook running Android 7.1.1 is not rooted, though the bootloader is unlocked. I am not accessing via any VPN.

**Comment by gzsombor** [comment] 2021-02-04 23:14
It was my manual bug-filling-form template :wink: 

Thanks for the answers!
I think, this bug is already fixed, and even F-Droid has 2.977 - https://f-droid.org/en/packages/free.rm.skytube.oss/
Please update your app!

**Comment by gzsombor** [comment] 2021-02-04 23:17
Duplicate of #863

**Comment by arkdae** [comment] 2021-02-05 00:27
I agree this is a duplicate of #863 . Unfortunately, now the comments don't work again due to the "reCaptcha Challenge Requested" as I wrote in my other bug report #910 . So it is probably the same issue for both of them.

Thanks for your support.

**Comment by gzsombor** [comment] 2021-02-05 08:09
Thanks, I've opened a separate feature request about reCaptchas: #912

**Closed by gzsombor** 2021-02-05 08:09 UTC
Labels: bug, duplicate

**Comment by drogga** [comment] 2021-02-05 10:41
@gzsombor Please edit\replace the "phone" from the templates to "device" as it's incorrect, android and the app can run on varies of devices - from watch to refrigerator (including in a car with Android Auto as board PC's OS). Thanks.

**Comment by drogga** [comment] 2021-02-05 16:36
@gzsombor Also I could not notice that the screenshots from the readme.md are broken and don't load\show-up after the moving of the repo to a organization...

**Comment by gzsombor** [comment] 2021-02-05 20:20
Interesting, they point to https://ram-on.github.io/SkyTube/assets/img/screenshots/* But nothing is there anymore.

**Comment by drogga** [comment] 2021-02-06 01:39
...still not showing up..., says "Not Found" if I try to open them.

**Comment by drogga** [comment] 2021-02-06 09:54
@gzsombor
...still not showing up..., says "Not Found" if I try to open them.
Maybe try reLinking the 6 of them directly to this path: https://github.com/SkyTubeTeam/SkyTube/tree/master/screenshots
