### ISSUE TITLE
Failure to open

### ISSUE THREAD

**Issue by Siameese** [SkyTubeTeam/SkyTube#1273] opened 2024-07-09 22:04 UTC
*Describe the bug**
None of the videoos i have will open and play, there was a storm here before that it worked..tried starting up by on and off of my tablet new update clearing cache im afraid to remove the app for i have downloads and not a memory card yet on my tablet
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem, or the link for the video, where You've found the issue

**Setup:**
 - Android version: [e.g. 7 or 10, etc]
 - Is Your device rooted?
 - Do You use Tor or any VPN service with your device?
 - App source [e.g. FDroid, Downloaded from GitHub, self build]
 - App Version [e.g. v2.977]
 - App Flavour [e.g. Extra or OSS]

**Additional context**
I have no tor working or vpn only a bleu light filter
My device is a black vieuw tablet and my mobile is a Nokia now the videoos play on my Nokia but the sound is missing? Also on my tablet the videoos were blurry

**Comment by grega1205** [comment] 2024-07-10 00:05
I am having the same issue today. Thumbnails are OK but when you click on them to play a video nothing happens, just a black screen with the player controls but no video loads

**Comment by Samylol99** [comment] 2024-07-10 01:33
It's same for me guys, I suspect Youtube updated something with it's API. This seems the most logical explanation (btw I tried deleting the app and re downloading it, it didn't help so I'm 90% sure the problem is from yt)

**Comment by Siameese** [comment] 2024-07-10 08:47
Hi guys maby this makes things more clear i get response code 403
When i restarted my mobile the videos also did not start
I looked up how to fix it but thats out of my league

**Comment by gzsombor** [comment] 2024-07-11 17:23
That's the same as https://github.com/TeamNewPipe/NewPipe/issues/11255 and https://github.com/TeamNewPipe/NewPipeExtractor/pull/1191 . It seems to be fixed in the extractor, so it can be fixed in SkyTube too.

**Comment by gzsombor** [comment] 2024-07-15 05:32
Fix released in v2.989

**Closed by gzsombor** 2024-07-15 05:32 UTC
Labels: bug
