### ISSUE TITLE
New version 2.988 problem to open any video

### ISSUE THREAD

**Issue by SiampanisP** [SkyTubeTeam/SkyTube#1277] opened 2024-07-12 09:34 UTC
App Android 2.988 can not locate any video to play. 
Result is 404 can't open video URL.

**Comment by SiampanisP** [comment] 2024-07-12 09:42
Correction Response 403 not 404

**Comment by mckaygerhard** [comment] 2024-07-13 00:14
duplicate of #1278  close it please

**Comment by mckaygerhard** [comment] 2024-07-13 00:16
duplicate of https://github.com/SkyTubeTeam/SkyTube/issues/1273 please close it

**Closed** 2024-07-14 10:17 UTC
Labels: bug

**Comment by SiampanisP** [comment] 2024-07-14 10:18
Reopen and closed as not planned
I don't understand Turkish.
English please.
