### ISSUE TITLE
Playlists: automatic sequential play

### ISSUE THREAD

**Issue by kevjonesin** [SkyTubeTeam/SkyTube#413] opened 2019-03-03 18:33 UTC
Is there a way to allow videos in YouTube channel playlists to automatically play through sequentially, one into another? Rather than having to manually interact with the app to start another each time one finishes?

Also, side note, perhaps a custom in-app SkyTube playlist feature, independent of YouTube lists, might be something nice to implement at some point.

**Comment by gzsombor** [comment] 2021-05-04 07:34
Duplicate of #648

**Closed by gzsombor** 2021-05-04 07:34 UTC
Labels: enhancement
