### ISSUE TITLE
Importing subscription.csv causes app to crash

### ISSUE THREAD

**Issue by chris122380** [SkyTubeTeam/SkyTube#1033] opened 2022-03-14 17:18 UTC
I did a search for this under issues and did not find it. 

When trying to import the YouTube subscriptions the app crashes and never imports the subscriptions. 

This happens with both the f-droid and SkyTube Extra versions. 
SkyTube 2.980 on Oxygen OS 12 (Android 12).

**Comment by Mcfly2340** [comment] 2022-03-14 18:23
I too am experiencing this. Really hope this gets fixed

**Comment by Offerel** [comment] 2022-03-15 16:40
I have the same problem. As a workaround, you can search channels and/or videos and subscribe from there.

**Comment by silez** [comment] 2022-03-16 16:43
Yes true!
I exported the .csv file from youtube.

In the app is the file called "subscriptions.json". I renamed the file subscriptions.csv to subscriptions.json. Both files caused an app-crash.
Happened with Galaxy Note 20 Ultra 5G, Android 12 and SkyTube 2.980 Extra (2022-02-03 00:50) officially downloaded at skytube-app.com.

Hope you can fix it because i don' t want to manually add all my over 300 subscriptions xDD 👍 🤣


Last but not least: You' re doing so damn well. Thank you for your nice app!

**Comment by sonicintrusion** [comment] 2022-03-18 17:04
csv and json are two different file formats so you can't just rename it like that.
i converted the csv into json using an online tool and the import doesn't crash the app but does show an error saying "cannot find any youtube channels in file".
it's probable that google has changed the export format and the skytube app hasn't been updated to match the fields yet.

**Comment by L31FY** [comment] 2022-03-23 00:18
The csv file makes the app crash and even when using tools to convert it to proper format json so it should be accepted it will either crash or not accept the input. There's definitely a bug here of some kind.

**Comment by silez** [comment] 2022-03-23 16:03
> [...] "cannot find any youtube channels in file". [...]

Yes! I converted the file too. No app crash anymore. but exact the same output as you reported.
Maybe it would be fixed soon. Would be very nice 🥰

**Comment by cindrmon** [comment] 2022-03-24 03:12
it still crashes for me. what version are you using?

> > [...] "cannot find any youtube channels in file". [...]
> 
> Yes! I converted the file too. No app crash anymore. but exact the same output as you reported. Maybe it would be fixed soon. Would be very nice 🥰

**Comment by silez** [comment] 2022-03-24 15:21
> it still crashes for me. what version are you using?
> 
> > > [...] "cannot find any youtube channels in file". [...]
> > 
> > 
> > Yes! I converted the file too. No app crash anymore. but exact the same output as you reported. Maybe it would be fixed soon. Would be very nice 🥰

I use the version SkyTube Extra 2.980 Extra (2022-02-03 00:50)

**Comment by gzsombor** [comment] 2022-04-16 09:45
Probably duplicate of #1046

**Closed by gzsombor** 2022-04-16 09:45 UTC

**Comment by chris122380** [comment] 2022-04-16 14:10
> Probably duplicate of #1046

Wouldn't 1046 actually be a duplicate of 1033? Wouldn't the smaller issue number he the older github issue? Meaning 1033 came before 1046 making 1046 the duplicate? 

Just trying to understand because when I created this issue I did a search and found no other issue relating to this (just trying to beat good github user).
