### ISSUE TITLE
Error 403 (all videos)

### ISSUE THREAD

**Issue by Darknir23** [SkyTubeTeam/SkyTube#1274] opened 2024-07-10 11:45 UTC
![Screenshot_20240709-163056](https://github.com/SkyTubeTeam/SkyTube/assets/175214994/a5af3b85-ca77-4110-85d5-5a5c0ab1db2b)

**Comment by Samylol99** [comment] 2024-07-11 01:08
Btw this is duplicate of #1273 eveyone is having this issue because yt updated something with it's code that makes current extraction flawed

**Comment by gzsombor** [comment] 2024-07-11 17:24
I'm closing as duplicate

**Closed by gzsombor** 2024-07-11 17:24 UTC
Labels: bug, duplicate
