### ISSUE TITLE
Videos aren't loading since today.

### ISSUE THREAD

**Issue by pgpierremb2** [SkyTubeTeam/SkyTube#1102] opened 2022-08-12 16:46 UTC
The latest version of SkyTube Extra version 2.981 isn't loading videos anymore, all other things are working including loading of feeds and comments. It just gets stuck in the loading GIF, no errors given or thrown.

**Comment by nomisunrider** [comment] 2022-08-12 22:55
Probably same issue newpipe has?

https://github.com/TeamNewPipe/NewPipe/issues/8760

**Comment by drogga** [comment] 2022-08-13 12:26
@gzsombor Please update the extractor.

**Comment by pgpierremb2** [comment] 2022-08-13 14:48
I believe SkyTube uses newpipe extractor, hence must be the same issue @nomisunrider pointed out. Will this be fixed anytime soon or most people don't use SkyTube?

**Comment by RandomModderJDK** [comment] 2022-08-13 21:47
I think the changes in https://github.com/TeamNewPipe/NewPipeExtractor/pull/891 should just be applied and then it should work again.

**Comment by RandomModderJDK** [comment] 2022-08-13 22:05
The problem is that newpipe needs to publish publish/ have an acceptable build, so that Skytube can update it. The best thin you can do is to use the official player.

**Comment by nomisunrider** [comment] 2022-08-13 23:38
New version of newpipe is out

**Comment by drogga** [comment] 2022-08-14 08:40
@pgpierremb2 - You can close this now.
@gzsombor - Please compile a release build, so I can install/update over the old one, because I prefer not having to backup and restore to the Snapshot build, which is with another package name (ID) and it's signed with a debug key.
I think that there's no need to have a major update with significant changes in order to push a new release, only the versionCode can be bumped to 42 and the versionName can stay at ...

**Comment by gzsombor** [comment] 2022-08-14 10:15
Can someone test with a Snapshot build? https://github.com/SkyTubeTeam/SkyTube/actions/runs/2853781139
As SkyTube works for me previously, probably this change only affects certain countries/territories.

**Comment by drogga** [comment] 2022-08-14 11:39
@gzsombor
I already did (as mentioned above in my previous comment), it works now ;)
Thanks for the fix.

**Comment by gzsombor** [comment] 2022-08-14 12:33
Thanks @drogga - and all the others who helped! I've created a new release!

**Closed by gzsombor** 2022-08-14 12:33 UTC

**Comment by drogga** [comment] 2022-08-25 13:20
@gzsombor
Nothing plays since today...
I'm not creating a new issue ticket regarding the same on purpose, since there's no point, given that this is here and the issue is well known - same old.

**Comment by drogga** [comment] 2022-08-25 13:25
@gzsombor
Nothing plays since today, once again updating the extractor is needed, NP fixed and released new vers., the cat and mouse game with google continues...
_I'm not creating a new issue ticket regarding the same on purpose, since there's no point, given that this is here and the issue is well known - same old._
