### ISSUE TITLE
CSV YouTube-Import

### ISSUE THREAD

**Issue by C-O-D** [SkyTubeTeam/SkyTube#1007] opened 2021-11-16 12:40 UTC
The YouTube data import in CSV format in V. 2.979 still doesn't work although the release notes say it should. Is this a misunderstanding by me?

**Comment by C-O-D** [comment] 2022-02-03 08:26
SkyTube Extra 2.980 still doesn't import abo.csv.
It simply does nothing after selecting the file and after two or three tries it crashes...
Can this PLEASE PLEASE PLEASE be fixed?

**Comment by saebaryo-xyz** [comment] 2022-02-03 20:57
Same issue with latest version on android 11

**Comment by L31FY** [comment] 2022-03-23 00:20
https://github.com/SkyTubeTeam/SkyTube/issues/1033

**Comment by C-O-D** [comment] 2022-04-16 06:23
SkyTube Extra 2.981 still doesn't import abo.csv!
AND still not even one response from the developer!
I mean, that's such an important feature, I don't get it...

**Comment by gzsombor** [comment] 2022-04-16 09:46
Probably duplicate of #1046

**Closed by gzsombor** 2022-04-16 09:46 UTC
Labels: bug
