### ISSUE TITLE
Problem with player

When i open a video i can' t play It.
I open the video and the screen Is black with the pause button and time 0:00-0:00.
I have a One plus nord without root

### ISSUE THREAD

**Issue by JLaruccia** [SkyTubeTeam/SkyTube#1275] opened 2024-07-11 05:22 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem, or the link for the video, where You've found the issue

**Setup:**
 - Android version: [e.g. 7 or 10, etc]
 - Is Your device rooted?
 - Do You use Tor or any VPN service with your device?
 - App source [e.g. FDroid, Downloaded from GitHub, self build]
 - App Version [e.g. v2.977]
 - App Flavour [e.g. Extra or OSS]

**Additional context**

**Comment by maaaat** [comment] 2024-07-11 13:20
Most likely another duplicate of #1273.

**Comment by mckaygerhard** [comment] 2024-07-13 00:19
yeah people just send issues like spamers and dont property search if the problem was already on topic

**Comment by gzsombor** [comment] 2024-07-13 11:46
Yes, I think, this is duplicate as well - at least, we can see, that there are users out there, who wants to use SkyTube :smile:

**Closed by gzsombor** 2024-07-13 11:46 UTC
Labels: bug
