### ISSUE TITLE
Preferred Resolution doesn't work

### ISSUE THREAD

**Issue by Sploof99** [SkyTubeTeam/SkyTube#415] opened 2019-03-13 21:56 UTC
Any time a video plays, it plays in the highest quality possible, even if both Preferred Resolution and Preferred Resolution are on a low setting. This has been happening for a the past few weeks now; nothing will load in 480p or below. Is this due to some change on YouTube's side of things?

**Comment by raixie1A** [comment] 2019-04-27 15:40
I noticed the same behaviour, it used all my bandwidth in the past couple of months.

**Comment by joshatt** [comment] 2019-04-28 07:43
Same here! Find this in Skytube old version months ago, so just now I upgraded to newest version, but it still plays a very high resolution while I've set it 144p.

**Comment by joshatt** [comment] 2019-04-28 08:00
> Added preferred resolution when using mobile network (instead of WIFI).
Is that so? but low resolution is needed even if under WIFI, especially when playing background (screen off), in this case low resolution means fast thus stable connection. Please consider.

**Comment by navid-zamani** [comment] 2020-11-28 21:14
To provide more detail: No matter what I set as the video player resoution, and no matter if the mobile download setting is 144p, it still downloads 360p and completely ruins my data cap!

And on wifi, it seems to ignore my 1080p setting ang download 720p instead.

This is a app-breaking feature as it's literally costing me money to risk using the app.

May I suggest changing the bug title to ”SkyTube ignores resolution settings“?

Please, please fix this before anything else.
I'm a developer too, although not for Android, so if you need any information, or non-ambiguois testing, I'll help you in any way I can.

My version of SkyTube: 2.975
My OS: EMUI 10.0.0.182 (Android 10)
Screen resolution: >HD

**Comment by gzsombor** [comment] 2020-11-28 23:57
The actual stream selection happens here: https://github.com/ram-on/SkyTube/blob/master/app/src/main/java/free/rm/skytube/businessobjects/YouTube/VideoStream/StreamMetaDataList.java

Without any detail how to reproduce your issues, I can only guess, that Youtube doesn't have the video in your requested resolution, so the app picked the first resolution - which could be a bad selection.

**Comment by navid-zamani** [comment] 2020-11-29 11:02
I’ve checked, and those videos were available in 144p. From personal experience, I know that 144p missing is very rare.

Can I assume that what SkyTube logs to, is what can be viewed with logcat? Because it logs if the resolution was not available, and then I could check.

I assumed it was very straightforward to reproduce my issue. Sorry.
Try this:
1. Set all three ressolution settings to 144p and for mobile downloads "always ask".
2. Disable wifi, and make sure you are on mobile data.
3. Download this video on which I just verified 144p is available but SkyTube downloads the 360p version: https://youtu.be/8zb92v5Vz40
4. Check its resolution in e.g. VLC.
Actual result: It says 640x360, and is over 60MB in size.
Expected result: It says 256×144 and is closer to 10MB in size. 

Could you tell me what resolution it downloads for you? And what version of SkyTube are you running? (I run the version given above, which is the latest one from F-Droid.)

It seems the code picks the first available resolution and returns, if the desired resolution is unknown. May I suggest checking if YouTube has changed the resolution IDs or if the end-to-end mapping is wrong in some other way?

Without running SkyTube in a debugger and stepping through the code while tracking the variables that store the resolution to pick and final URL, I can not track this down any further. Could you try that too, if it downloads the wrong resolution for you too?
(I'm on 3GB of data per every 4 weeks and only wifi if I stand outside in the freezing cold currently, so I can't download Android Studio to debug this myself. Never tried debugging an Android app either.)

**Comment by gzsombor** [comment] 2020-11-30 22:42
Thanks, yeah, Android Studio is pain to use, and it's a shame, that nothing else works for Android development - one of the reason why I lost my enthusiasm.
 Ok, I think, I know what's going on - the problem is that youtube provides multiple video and audio streams. And streams, which contains both. Unfortunately SkyTube only checks, if Youtube provides a merged video+audio stream with the desired resolution, doesn't try to combine the video and audio streams by itself. For this video, it provides 2 video+audio streams 360p and 720p, and 9 video only streams, and 4 audio only streams....

**Comment by gzsombor** [comment] 2021-02-01 23:24
This bug fix is already implemented

**Closed by gzsombor** 2021-02-01 23:24 UTC
Labels: bug
