### ISSUE TITLE
Could not start video 2.988

### ISSUE THREAD

**Issue by SiampanisP** [SkyTubeTeam/SkyTube#1278] opened 2024-07-12 09:41 UTC
Could not start video response 403
App Android 2.988

**Comment by mckaygerhard** [comment] 2024-07-13 00:14
duplicate of #1277

**Comment by mckaygerhard** [comment] 2024-07-13 00:15
duplicate of #1273 please close it

**Comment by SiampanisP** [comment] 2024-07-13 11:37
> duplicate of #1277 stop spaming @SiampanisP

Yes two identical issues but it is not a spam. Please think first before saying smart things.

Silly answers but no solutions to the problem.

**Comment by gzsombor** [comment] 2024-07-13 11:40
Based on the minimal description, I can't think anything else, that's must be duplicate of #1273

**Closed by gzsombor** 2024-07-13 11:40 UTC
Labels: bug, duplicate

**Comment by KlaasVogel** [comment] 2024-07-15 14:20
Hi @gzsombor,
nice job updating the app to V2.989.
quick question (I hope it's appropriate to drop it here):

I can only run SkyTube (not extra) on my Android TV. I tried using "Android Studio" to build a new apk, but it only generates an apk for SkyTube-Extra. Can you point me to any instructions to build the apk for free.rm.skytube.oss_??.apk ?
If I can build them myself, I might try to solve issue #1211 (no experience in working with Android Studio, so I'm not sure I'll succeed.

with kind regards,
Klaas
