### ISSUE TITLE
Live Broadcast Videos Not Working

### ISSUE THREAD

**Issue by ghost** [SkyTubeTeam/SkyTube#914] opened 2021-02-06 23:46 UTC
I have noticed that trying to watch a live broadcast video doesn't work. It seems to hang or creates an error. I am using the latest F-Droid version right now. Sorry I can't replicate this right now or be more specific.

**Comment by gzsombor** [comment] 2021-02-16 22:07
Thanks, yes, this is not an implemented feature, the duplicate of #42

**Closed** 2021-02-16 22:08 UTC
Labels: duplicate, enhancement
